name = "Rhai Module"
description = "Create a new Rhai module extension"
kickstart_version = 1

[[variables]]
name = "module"
default = "http"
prompt = "Write the short name of the module (without spaces)"

[[variables]]
name = "author"
default = "José F. Rives"
prompt = "Author name"

[[variables]]
name = "description"
default = ""
prompt = "Description of the module"